{% set name = "alt-profanity-check" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 704daad93b33c76e164021993f3776ffc74e733f0e9571ae5dd1f2be8e7e8c3f

build:
  entry_points:
    - profanity_check=profanity_check.command_line:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - scikit-learn ==1.5.1
    - joblib >=1.4.0

test:
  imports:
    - profanity_check
  commands:
    - pip check
    - profanity_check --help
  requires:
    - pip

about:
  home: https://github.com/dimitrismistriotis/alt-profanity-check
  summary: A fast, robust library to check for offensive language in strings. Dropdown replacement of "profanity-check".
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
