{% set name = "alt-profanity-check" %}
{% set version = "1.7.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 82bbeaf71872f8ab3846f82ff60c53c7207bdf2d312b336bcd204ab350dc4892

build:
  entry_points:
    - profanity_check=profanity_check.command_line:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - scikit-learn ==1.7.1
    - joblib ==1.5.1

test:
  imports:
    - profanity_check
  commands:
    - pip check
    - profanity_check --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dimitrismistriotis/alt-profanity-check
  summary: A fast, robust library to check for offensive language in strings. Dropdown replacement of "profanity-check".
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
